---
driver:
  name: vagrant
  synced_folders:
    - ["test/sync_fold","/vagrant"]

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 14.10.9

platforms:
  - name: centos-7.6
    driver:
      gui: false

suites:
  - name: default
    run_list:
      - recipe[supervisor::compile_python]
      - recipe[supervisor::default]
